spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/reserfy
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    locations:
      - classpath:db/migration